volumes:
  fedora:
  solr:

services:
  fedora:
    image: fcrepo/fcrepo:6.5.1-tomcat9
    volumes:
      - fedora:/data
    environment:
      - CATALINA_OPTS=-Dfcrepo.autoversioning.enabled=false
    ports:
      - '8986:8080'

  solr:
    image: solr:9
    volumes:
      - ./solr/conf:/opt/solr/core_conf
      - solr:/var/solr
    command:
      - solr-precreate
      - hydra-test
      - /opt/solr/core_conf
    environment:
      - SOLR_MODULES=analysis-extras,extraction
    ports:
      - '8985:8983'

