version: 2.1
orbs:
  samvera: samvera/circleci-orb@1
jobs:
  bundle_and_test:
    parameters:
      ruby_version:
        type: string
      rails_version:
        type: string
      bundler_version:
        type: string
        default: 2.0.2
      ffmpeg_version:
        type: string
        default: 4.1.4
    executor:
      name: 'samvera/ruby_fcrepo_solr'
      ruby_version: << parameters.ruby_version >>
      solr_version: 8-slim
    environment:
      RAILS_VERSION: << parameters.rails_version >>
    working_directory: ~/project
    steps:
      - samvera/cached_checkout

      - samvera/bundle:
          ruby_version: << parameters.ruby_version >>
          bundler_version: << parameters.bundler_version >>

      - samvera/rubocop

      - samvera/install_solr_core

      - samvera/parallel_rspec

workflows:
  ci:
    jobs:
      - bundle_and_test:
          name: "ruby2-7_rails7-0"
          ruby_version: "2.7.6"
          rails_version: "7.0.4"
      - bundle_and_test:
          name: "ruby2-7_rails6-1"
          ruby_version: "2.7.6"
          rails_version: "6.1.7"
      - bundle_and_test:
          name: "ruby2-7_rails6-0"
          ruby_version: "2.7.6"
          rails_version: "6.0.6"
      - bundle_and_test:
          name: "ruby2-7_rails5-2"
          ruby_version: "2.7.6"
          rails_version: "5.2.8.1"
