version: 2.1
orbs:
  samvera: samvera/circleci-orb@1
jobs:
  bundle_and_test:
    parameters:
      ruby_version:
        type: string
      rails_version:
        type: string
      bundler_version:
        type: string
        default: 2.5.18
      ffmpeg_version:
        type: string
        default: 4.1.4
    executor:
      name: 'samvera/ruby_fcrepo_solr'
      ruby_version: << parameters.ruby_version >>
      solr_version: 8-slim
    environment:
      RAILS_VERSION: << parameters.rails_version >>
    working_directory: ~/project
    steps:
      - samvera/cached_checkout

      - samvera/bundle:
          ruby_version: << parameters.ruby_version >>
          bundler_version: << parameters.bundler_version >>

      - samvera/rubocop

      - samvera/install_solr_core

      - samvera/parallel_rspec

workflows:
  ci:
    jobs:
      - bundle_and_test:
          name: "ruby3-3_rails7-2"
          ruby_version: "3.3.4"
          rails_version: "7.2.1"
      - bundle_and_test:
          name: "ruby3-2_rails7-1"
          ruby_version: "3.2.5"
          rails_version: "7.1.4"
      - bundle_and_test:
          name: "ruby3-1_rails7-1"
          ruby_version: "3.1.6"
          rails_version: "7.1.4"
      - bundle_and_test:
          name: "ruby3-2_rails7-0"
          ruby_version: "3.2.5"
          rails_version: "7.0.8.4"
      - bundle_and_test:
          name: "ruby3-1_rails7-0"
          ruby_version: "3.1.6"
          rails_version: "7.0.8.4"
